### ISSUE TITLE
Deferring loading of DyNet on import

### ISSUE THREAD

**Issue by BLKSerene** [taishi-i/nagisa#10]
Hi, I'm using nagisa in my GUI-based project. When importing nagisa, it requires a few seconds to load DyNet, adding extra time to the loading time of my program, so I have to defer the import of nagisa until it is needed.
I'm not sure whether DyNet is required by all functions of nagisa, but I think that it would be better if the loading of DyNet is deferred until it is needed by nagisa the first time.

**Comment by taishi-i** [comment]
Thanks for using nagisa. I understand the problem that takes a few seconds to import. Actually, it takes  a few seconds to build neural networks when importing.

Could you tell me your execution environment and how many seconds will it take in it?
Could you also tell me the version of Python? Python 2 takes longer than Python 3. So, I recommend you use nagisa on Python3.6.
 
For your information, it takes 1.24 s in my desktop PC environment using Python3.6 to imoprt nagisa.
