### ISSUE TITLE
Drop support for Python2.7?

### ISSUE THREAD

**Issue by BLKSerene** [taishi-i/nagisa#15]
The [EOL of Python2.7](https://pythonclock.org/) is January 1, 2020.
As [many other major open-source project](https://python3statement.org/), is there any plan for a new version of nagisa that will drop support for Python2.7 and support only Python3?

The Python3-only version could remove the dependency of six and lighten the burden of maintenance work in the future.

**Comment by taishi-i** [comment]
Hi @BLKSerene .
Sorry for the late reply and thank you for the valuable information.

We don't drop support for Python2.7 and will continue to support it as much as possible.
However, if there is a big advantage to quit support for Python2.7, there is a possibility to change the policy. In that case, we will contact you again. Thank you.

**Comment by BLKSerene** [comment]
Okay, I got it. Thanks anyway!

**Comment by BLKSerene** [comment]
The README has officially dropped Python 2 support, so I think the `six` dependency could be get rid of now.
