### ISSUE TITLE
Why do you have 6 dim outputs for word segmentation?

### ISSUE THREAD

**Issue by wannaphong** [taishi-i/nagisa#21]
from https://github.com/taishi-i/nagisa/blob/master/nagisa/model.py#L59, Why do you have 6 DIM outputs for word segmentation? `encode_ws` has 6 DIM outputs.  I understand you using BMES (4 dim first). What are the last two boxes used for? Could you explain that, please?

Thank you.

**Comment by taishi-i** [comment]
Hi @wannaphong, thank you for your question.

Yes, I use the BMES(4 dims) for word segmentation.
The remaining 2 dims are the special tokens (Start of Sentence: SOS ans End of Sentence: EOS).

The CRF layer of the BiLSTM-CRF uses the transitions matrix to calculate tag dependencies.
It means that the M tag frequently occurs after the B tag and the E tag frequently occurs after the M tag. To implement this function, it needs the special tokens (SOS and EOS).
The special tokens represent that the B tag frequently occurs after the SOS token and the E tag frequently occurs next to EOS tag.

I refer to the BiLSTM-CRF model architecture https://www.aclweb.org/anthology/N16-1030/ and its original implementation https://github.com/glample/tagger/blob/1c9618889fb89500cc5e70c45c27859b89d44449/model.py#L285.

Thank you.

**Comment by wannaphong** [comment]
Thank you. 👍
