### ISSUE TITLE
About referecnce this library

### ISSUE THREAD

**Issue by mrpeerat** [taishi-i/nagisa#22]
I want to citation this library, and I want to know you have any paper or journal to read more about this library work or Bibtext for citation?

**Comment by taishi-i** [comment]
Hi @mrpeerat, thank you for using this tool. Please cite the following BibTeX.

```
@misc{ikeda2018nagisa,
  author = {Taishi Ikeda},
  title = {nagisa: A Japanese tokenizer based on recurrent neural networks},
  year = {2018},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github. com/taishi-i/nagisa}},
}
```

I'm sorry that I publish the paper only in Japanese. So, if you want to know about word segmentation method, please refer to the this attach file [Japanese_Word_Segmentation_using_Character-level_Recurrent_Networks_with_Dictionary_Information.pdf](https://github.com/taishi-i/nagisa/files/4492584/Japanese_Word_Segmentation_using_Character-level_Recurrent_Networks_with_Dictionary_Information.pdf).

Please let me know when your paper is published.
Thank you.

**Comment by mrpeerat** [comment]
Thank you so much

**Comment by wannaphong** [comment]
@taishi-i Hello. This paper is `Domain Adaptation of Thai Word Segmentation Models using Stacked Ensemble` at https://aclanthology.org/2020.emnlp-main.315/.

Thank you.

**Comment by mrpeerat** [comment]
> @taishi-i Hello. This paper is `Domain Adaptation of Thai Word Segmentation Models using Stacked Ensemble` at https://aclanthology.org/2020.emnlp-main.315/.
> 
> Thank you.

Also, Handling Cross- and Out-of-Domain Samples in Thai Word Segmentation https://aclanthology.org/2021.findings-acl.86/
