### ISSUE TITLE
Pip/pip3 install nagisa Error

### ISSUE THREAD

**Issue by ssaikiran123** [taishi-i/nagisa#23]
Hello @taishi-i  when i am trying to pip install nagisa getting below error. I tried to install through conda.

Windows7
C:\Users\SAIKIRAN>python --version
Python 3.8.3

Error: 
ERROR: Command errored out with exit status 1: 'c:\users\saikiran\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0
= '"'"'C:\\Users\\SAIKIRAN\\AppData\\Local\\Temp\\pip-install-a31d0hp1\\DyNet\\setup.py'"'"'; __file__='"'"'C:\\Users\\SAIKIRAN\\AppData\\Local\\Temp\\pip-install-a31d0
1\\DyNet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '
"'exec'"'"'))' install --record 'C:\Users\SAIKIRAN\AppData\Local\Temp\pip-record-mg2btvbb\install-record.txt' --single-version-externally-managed --compile Check the lo
 for full command output.

**Comment by taishi-i** [comment]
Hi @ssaikiran123, 
Could you tell me the result of the following command to see if the Windows you are using is 32 (x86) or 64 bit (AMD64)?

`echo %PROCESSOR_ARCHITECTURE%`

If it's x86, this is the reason why you can't install it.
I will prepare a solution to this problem for you.

Thank you

**Comment by ssaikiran123** [comment]
Hello @taishi-i 
Please find below
C:\Users\SAIKIRAN>echo %PROCESSOR_ARCHITECTURE%
AMD64
I am using windows7 64 bit. with 4.00gb RAM

The Error mentioned is common to most of the japanese libraries including nagisa
ERROR: Command errored out with exit status 1:

**Comment by taishi-i** [comment]
Hi @ssaikiran123,
Thank you for sharing your information. I don't think it seems to be a hardware problem.
Sorry. I didn't realize you were using python 3.8.3 _Nagisa_ doesn't support python 3.8.*
So, is it possible to try it with Python 3.7.*?

Python 3.7.7
https://www.python.org/downloads/release/python-377/
Anaconda for Python 3.7.7
https://repo.anaconda.com/archive/Anaconda3-2020.02-Windows-x86_64.exe

**Comment by ssaikiran123** [comment]
Hello @taishi-i 
i suspected it to be pythpn version issue and tried it on python 2.7 but it asked for python 3.6 requirement so i installed python 3.6 and when i tried to pip install nagisa and then i am receiving

 SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.

Later i tried pip install python-dev-tools and still facing same issue
C:\Users\SAIKIRAN>python --version
Python 3.6.4

**Comment by taishi-i** [comment]
Hi @ssaikiran123, 
If you're getting an error with _polyglot_ as well, it's probably a python's problem.
I want to make sure of the following thing. 
Do you see the following message (error: Microsoft Visual C++ 14.0 is required.) above the error (ERROR: Command errored out with exit status 1:)?

```
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\taishi\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\taishi\\AppData\\Local\\Temp\\pip-install-mz79w8he\\nagisa\\setup.py'"'"'; __file__='"'"'C:\\Users\\taishi\\AppData\\Local\\Temp\\pip-install-mz79w8he\\nagisa\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\taishi\AppData\Local\Temp\pip-record-cblnkriv\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
```

**Comment by ssaikiran123** [comment]
Hello @taishi-i 

No such ask because i already installed visual c++.


C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Visual C++ Build Tools\Windows Desktop Command Prompts> 

i tried to pip install here but still same issue and now its asking for cmake 
CMake suite maintained and supported by Kitware (kitware.com/cmake).
error: `make` not found, and `MAKE` is not set.

**Comment by taishi-i** [comment]
Hi @ssaikiran123,
If you get `error: make not found, and MAKE is not set.`,  could you install the latest `Build Tools for Visual Studio 2019` via the following link? https://visualstudio.microsoft.com/downloads/

Tools for Visual Studio 2019
⇒ Build Tools for Visual Studio 2019

![Screenshot from 2020-06-19 03-14-17](https://user-images.githubusercontent.com/12726223/85057290-8a08ad00-b1db-11ea-9a49-87ee9b56734b.png)

Select c++ build tools and the option on the right in the installer and try to install it as follows.

![Annotation 2020-06-19 030856](https://user-images.githubusercontent.com/12726223/85057513-cdfbb200-b1db-11ea-93d2-5a44a3059db8.png)

I could install _nagisa_ on my Windows PC in this way.

**Comment by ssaikiran123** [comment]
Hello @taishi-i 

I am doing as suggested downloading its taking time as its 1.35gb data will update you the result today evening thank you

**Comment by ssaikiran123** [comment]
Hello @taishi-i 

I did as suggested and downloaded the build tools for visual studio 2019 but still facing same issue

**Comment by taishi-i** [comment]
Hi @ssaikiran123,
Thank you for trying out my suggestions.
I would like to check at what stage the error and understand the cause of the installation failure.

1. Is it okay to install cython?
```
pip install cython
```

```
# This is a message in case of success
Installing collected packages: cython
Successfully installed cython-0.29.20
```

2. Is it okay to install dynet?
```
pip install dynet
```

```
# This is a message in case of success
Installing collected packages: numpy, dynet
Successfully installed dynet-2.1 numpy-1.18.5
```

3. Is it okay to install nagisa?
```
pip install nagisa
```

```
# This is a message in case of success
Installing collected packages: six, nagisa
Successfully installed nagisa-0.2.6 six-1.15.0
```

4. Is it okay to import nagisa?
```
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nagisa
[dynet] random seed: 1234
[dynet] allocating memory: 32MB
[dynet] memory allocation done.
>>> nagisa.__version__
'0.2.6'
>>> 
```

**Comment by taishi-i** [comment]
Hi @ssaikiran123,
I have modified the codes so that windows users can install naigsa without Build Tools.
Could you try the following command to install it?
```
pip install git+https://github.com/taishi-i/nagisa.git@nagisa-without-cython
```

Thank you.

**Comment by ssaikiran123** [comment]
Hello Taishi-I/Nagisa

Sure I'll do as suggested and share the result currently I am updating my
windows to windows10.

Thanks & Regards
Saikiran

**Comment by ssaikiran123** [comment]
Hello @taishi-i 

Thanks for modifying the code . Not sure was it my windows7 os issue or not, Anyway i upgraded to windows10 and tried to install using  pip install git+https://github.com/taishi-i/nagisa.git@nagisa-without-cython and was able to.
![image](https://user-images.githubusercontent.com/59430646/85234165-1d82ed80-b429-11ea-8043-e6c8c6779a18.png)

**Comment by taishi-i** [comment]
Hi @ssaikiran123,
Thank you for taking the time to respond to this issue. Good luck!
