### ISSUE TITLE
Is it possible to apply pos-tagging to a list of words, which was already tokenized?

### ISSUE THREAD

**Issue by ichiroex** [taishi-i/nagisa#8]

**Comment by taishi-i** [comment]
Hi @ichiroex 

Yes, it is possibile to apply pos-tagging to a list of tokenized words.
However, I need to rewrite some existing codes.
I will inform you after rewriting the codes. Please wait a few days.

**Comment by ichiroex** [comment]
Thank you for your quick reply.
I'm looking forward to  the function 👍

**Comment by ichiroex** [comment]
Thank you for your prompt attention to this matter.
It's very nice! I'll use this wonderful function 👯
